services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.vrt
    volumes:
      - .:/app
      - /app/node_modules
      - pnpm-store:/pnpm-store
    working_dir: /app
    command: sh -c "pnpm install --store-dir /pnpm-store && pnpm exec playwright test"
    environment:
      - NODE_ENV=test
      - DOCKER=true
    ipc: host
    ports:
      - "9323:9323"


volumes:
  pnpm-store:
